config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'statics/home'
  get 'statics/cost'
  get 'statics/travel'
  get 'statics/contacts'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'statics#home'
  resources :orders

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/building.rb
class Building < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/place.rb
class Place < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
	validates_uniqueness_of :email
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :confirmable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

before_action :authenticate_user!

before_action :set_order, only: [ :show, :edit, :update, :destroy ]

  def index
  	@orders = Order.all
  end

 def show
   end

  def new
  	@order = Order.new
  end

  def create
  	@order = Order.new(order_params)
  	if @order.save
       redirect_to @order, success: 'Post created'
     else
       render :new, danger: 'Post not created'
     end
  end

  def edit
  end

  def update
  	if @order.update_attributes(order_params)
      redirect_to @order, info: 'Order updated'
    else
      render :edit, danger: 'Order not updated'
    end
  end 

  def destroy
		@order.destroy
		redirect_to orders_path, success: 'Order destroyed'
  	end

private
def order_params
    params.require(:order).permit(:order_id, :user, :place, :cost, :data_from, :data_to, :status)
	end

def set_order
		@order = Order.find(params[:id])
	end

end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController
  def home
  end

  def cost
  end

  def travel
  end

  def contacts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def bootstrap_class_for(name)
    {
        success: "alert-success",
        error: "alert-danger",
        danger: "alert-danger",
        alert: "alert-warning",
        notice: "alert-info"
    }[name.to_sym] || name
  end
end

app/helpers/statics_controller_helper.rb
module StaticsControllerHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Car Park 24</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class = "container">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <ul class="nav navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="<%= root_path %>"> CarPark24 </a>
      </li>

      <li class="nav-item">
        <a class="nav-link" href="<%= statics_cost_url %>"> Стоимость </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= statics_travel_url %>"> Проезд </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= statics_contacts_url %>"> Контакты </a>
      </li>
    </ul>

   <%#  <ul class="navbar-nav pull-xs-right">
   <%# <%= link_to 'Бронирование', new_order_path, class: 'btn btn-outline-primary pull-xd-right' %>

   <%#  <%= link_to 'Панель управления', orders_path, class: 'btn btn-outline-primary pull-xd-right' %> 

   <ul class="navbar-nav offset-md-5">

          <% if user_signed_in? %>
            <li><a href="<%= new_order_path %>"><%= 'Сделать заказ' %></a></li>
              <% if current_user.admin? %>
                <li><a href="<%= orders_path %>"><%= 'Панель управления' %></a></li>
              <%end%>
              <li style="float:right">
                 <%= link_to 'Выход', destroy_user_session_path, method: :delete%>
              </li>
          <% else %>
            <li style="float:right" class="navbar-nav offset-md-10">
                <%= link_to 'Регистрация', new_user_registration_path %>
               </li>
              <li style="float:right"class="navbar-nav offset-md-1">
                <%= link_to 'Вход', new_user_session_path %>
             </li>
          <% end %>
        </ul>

  </nav>
  </div>

<div class = "container main">
    <div class="row">
      <div class="col-md-12">
        <% flash.each do |name, message| %>
          <div class="alert <%= bootstrap_class_for(name) %>">
           <%#  <% <button class="close" data-dimiss="alert">&times;</button> %>
            <%= message %>
          </div>
        <% end %>
      </div>
    </div>
    <%= yield %>
  </div>

  </body>
</html>

app/views/orders/_form.html.erb
<%= form_for @order do |f| %>

	<div class = "form-group">
		<%= f.label :user %>
		<%= f.text_field :user, class: 'form-control' %>
	</div>

	<div class = "form-group">
		<%= f.label :place %>
		<%= f.number_field :place, class: 'form-control' %>
	</div>

	<div class = "form-group">
		<%= f.label :cost %>
		<%= f.number_field :cost, class: 'form-control' %>
	</div>

	<div class = "form-group date">
		<%= f.label :date_from %>
		<%= f.date_select :date_from, class: 'form-control' %>
	</div>

	<div class = "form-group date">
		<%= f.label :date_to %>
		<%= f.date_select :date_to, class: 'form-control' %>
	</div>

	<div class = "form-group date">
		<%= f.submit 'Подтвердить', class: 'btn btn-primary' %>
		<%= link_to 'Назад', :back, class: 'btn btn-outline-secondary' %>
	</div>
<% end %>

app/views/orders/_order.html.erb
	<article class="order">
    <section class="order-head">
      <h3><%= link_to order.user, order_path(order) %></h3>
      <small>
        <time><%= order.date_from %> / <%= order.date_to %></time>
       	<div>Место: <%= order.place %> / Стоимость:<%= order.cost %></div>
          <% if user_signed_in? %>
          <%= link_to 'Редактировать', edit_order_path(order) %>
          |
          <%= link_to  'Удалить', order_path(order), method: :delete, data: {confirm: 'Подтврдите удаление'} %>
          <% end %>
      </small>
    </section>
  </article>

app/views/orders/edit.html.erb
<h1>Редактирование</h1>

<%= render 'form' %>

app/views/orders/index.html.erb
<h1>Список заказов<h1>

<%= render @orders %>

app/views/orders/new.html.erb
<h1>Бронирование</h1>

<%= render 'form' %>

app/views/orders/show.html.erb
  <article class="order">
    <section class="order-head">
      <h1><%= @order.user %></h1>
      <small>
        <time><%= @order.date_from %> / <%= @order.date_to %></time>
        <% if user_signed_in? %>
          |
          <%= link_to 'Редактировать', edit_order_path(@order) %>
          |
          <%= link_to  'Удалить', order_path(@order), method: :delete, data: {confirm: 'Подтврдите удаление'} %>
          <% end %>
      </small>
    </section>
    <section class="order-body">
      Место: <%= @order.place %> / Стоимость:<%= @order.cost %>
    </section>
  </article>

app/views/statics/contacts.html.erb
<h1>Наши телефоны:</h1>
<p>8-916-134-75-52 (Никита)</p>
<p>8-916-134-75-53 (Станислав)</p>

<h1>Наша почта:</h1>
<p>petrovn.00@mail.ru</p>

app/views/statics/cost.html.erb
<h1>Стоимость услуг</h1>
<p>200 рублей/сутки - тариф при парковке на срок до 7 дней</p>
<p>150 рублей/сутки - тариф при парковке на срок более 7 дней</p>

app/views/statics/home.html.erb
<h1>Долгосрочная парковка Car Park 24</h1>
<p>Сервис "Car Park 24" предоставляет услуги долгосрочной парковки с 2020 года. С каждым днем вопрос о парковочных местах становится все актуальнее. Увеличивающийся поток автомобилей требует развития автопарковок. Наша команда стремится создать доступный и максимально удобный парковочный сервис.</p>
<p>Территория парковки расположена в шаговой доступности от терминала.</p>
<p>Авторизируйтесь, чтобы забронировать порковочное место, или воспользуйтесь нашими телефонными линиями.</p>

<%= image_tag "parking.jpg" %>  

app/views/statics/travel.html.erb
<h1>Описание схемы проезда</h1>
<p>Парковка расположена в шаговой доступности от терминала.</p>
<p>При подъезде к аэропорту на развилке держаться левее. После развилки повернуть направо на первом же повороте. Для наглядности приведена схема проезда. Сразу за поворотом находится КПП - въезд на территорию парковки. Внимание: движение одностороннее!</p>

<%= image_tag "shema.png" %>  